version: '3'
services:
  neo-db:
    image: neo4j:5.12.0
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
    volumes:
      - ./neo4j/plugins:/plugins
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8000:8000
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=12345678
      - OPENAI_API_KEY=YOUR_OPENAI_API_KEY
      - OPENAI_HOST=https://api.openai.com/v1
    env_file:
      - .env
    depends_on:
      - neo-db
